##
name: 'TYPO3 CI Copy Paste Detector'
description: 'GitHub Action that checks for any copy paste occurrences in your code.'
branding:
  icon: check
  color: orange
runs:
  using: 'docker'
  image: 'Dockerfile'
